name: Setup Script Test

on:
  workflow_dispatch: 
  push:
    branches: [ "main" ]
    # 以下のファイルに変更があれば実行される。
    paths:
      - 'setup.sh'
      - '*.sh'
      - '.github/workflows/**'
jobs:
  test-setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Execute setup.sh
        run: |
          chmod +x setup.sh
          yes | ./setup.sh
